import { buildSession, finishSession } from '../../domain/session'
import type { ExercisePrescription, Prescription, TemplateId, WorkoutSession, WorkoutTemplate } from '../../domain/types'

/**
 * Realistic sample history for the charts and ladders, generated by playing a
 * scripted run of workouts through the real progression engine so every demo
 * record is internally consistent. Demo sessions never feed real targets.
 */

const DAY_MS = 24 * 60 * 60 * 1000
const MIN_MS = 60 * 1000

/** Where the demo lifter started, a couple of steps below the user's current loads. */
const DEMO_START: Record<string, ExercisePrescription> = {
  'pull-ups': { kind: 'reps', loadKg: -5, reps: [5, 5, 5] },
  dips: { kind: 'reps', loadKg: -5, reps: [5, 5, 5] },
  'db-row': { kind: 'reps', loadKg: 14, reps: [5, 5, 5] },
  'db-bench': { kind: 'reps', loadKg: 12, reps: [5, 5, 5] },
  'db-press': { kind: 'reps', loadKg: 8, reps: [5, 5, 5] },
  'hammer-curls': { kind: 'reps', loadKg: 8, reps: [8, 8] },
  'reverse-crunch': { kind: 'reps', loadKg: 10, reps: [10, 10, 10] },
  'suitcase-carry': { kind: 'timed', loadKg: 14, seconds: 40, setsPerSide: 2 },
  'bulgarian-split-squat': { kind: 'reps', loadKg: 8, reps: [5, 5, 5] },
  'single-leg-rdl': { kind: 'reps', loadKg: 12, reps: [5, 5, 5] },
  'hip-thrust': { kind: 'reps', loadKg: 30, reps: [5, 5, 5] },
  'sliding-hamstring-curl': { kind: 'reps', loadKg: 0, reps: [8, 8] },
  'copenhagen-plank': { kind: 'timed', loadKg: 0, seconds: 20, setsPerSide: 2 },
}

/** Deterministic PRNG (mulberry32) so the demo is identical on every install. */
function createRandom(seed: number): () => number {
  let state = seed >>> 0
  return () => {
    state = (state + 0x6d2b79f5) >>> 0
    let t = state
    t = Math.imul(t ^ (t >>> 15), t | 1)
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

export interface DemoOptions {
  now: number
  templates: Record<TemplateId, WorkoutTemplate>
  count?: number
  successRate?: number
}

/** Days between consecutive demo workouts, cycling: three workouts a week. */
const GAP_DAYS = [3, 2, 2]

export function generateDemoHistory({ now, templates, count = 24, successRate = 0.6 }: DemoOptions): WorkoutSession[] {
  const random = createRandom(0x0eb1)

  // Scheduled backwards from two days ago at 18:10 local time.
  const last = new Date(now - 2 * DAY_MS)
  last.setHours(18, 10, 0, 0)
  const starts: number[] = [last.getTime()]
  for (let i = 1; i < count; i++) starts.unshift(starts[0] - GAP_DAYS[i % GAP_DAYS.length] * DAY_MS)

  // One set of targets across both workouts, so the shared jump rope keeps growing.
  const current = new Map<string, Prescription>()
  for (const template of Object.values(templates)) {
    for (const exercise of template.exercises) current.set(exercise.id, DEMO_START[exercise.id] ?? exercise.baseline)
  }
  current.set('jump-rope', { kind: 'warmup', durationSec: 60, active: true })

  const sessions: WorkoutSession[] = []
  starts.forEach((startedAt, index) => {
    // Oldest first, alternating like the real plan and starting with upper body.
    const template = templates[index % 2 === 0 ? 'upper' : 'lower']
    let session = buildSession({
      id: `demo-${String(index + 1).padStart(2, '0')}`,
      now: startedAt,
      template,
      prescriptions: current,
      source: 'demo',
    })

    session = {
      ...session,
      warmup: session.warmup.map((step) => {
        if (!step.active) return step
        const completed = step.stepId !== 'jump-rope' || random() < 0.9
        const fullMs = step.plannedSec * 1000 * (step.perSide ? 2 : 1)
        return { ...step, completed, elapsedMs: completed ? fullMs : fullMs * 0.7 }
      }),
      exercises: session.exercises.map((exercise) => {
        const success = random() < successRate
        if (exercise.kind === 'reps') {
          const shortSet = exercise.actual.length - 1
          return {
            ...exercise,
            actual: exercise.actual.map((set, i) => ({
              ...set,
              status: 'done' as const,
              reps: !success && i === shortSet ? Math.max(1, set.reps - 1) : set.reps,
            })),
          }
        }
        const shortEffort = exercise.actual.length - 1
        return {
          ...exercise,
          actual: exercise.actual.map((effort, i) => ({
            ...effort,
            status: 'done' as const,
            seconds: !success && i === shortEffort ? Math.max(5, effort.seconds - 8) : effort.seconds,
          })),
        }
      }),
    }

    const durationMs = (40 + Math.floor(random() * 12)) * MIN_MS
    const finished = finishSession(session, { now: startedAt + durationMs })
    const completed: WorkoutSession = { ...finished, lastInteractionAt: startedAt + durationMs, rev: 1 }
    sessions.push(completed)

    for (const [targetId, recommendation] of Object.entries(completed.recommendations ?? {})) {
      current.set(targetId, recommendation.prescription)
    }
  })

  return sessions
}
